In [ ]:
# Data Dividation
# workfolw of ml
# Data ingestion ---> Data cleaning and preprocessing ---> Based on the target column
# we have to select ml model ---> model training ---> model prediction ---> model preforance
# Evaluation

In [ ]:
# # df---> x(input) , y(target)
# x ----> x_train  ,x_test
# y ----> y_train  ,y_test
# model training( x_train  ,y_train)
# y_pred = model prediction(x_test , y_)

In [ ]:
# 1+1=2
# 1+2=3
# 1+3=4
# 1+4=5
# x = [1+1,1+2,1+3,1+4]
# y = [2,3,4,5]
# x_train = [1+1,1+2,1+3]
# y_train=[2,3,4]
#x_test=[1+4]
#y_test =[5]

In [1]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv("/content/placement.csv")

In [22]:
df.head(2)

   cgpa  resume_score  placed
0  8.14          6.52       1
1  6.17          5.17       0

In [5]:
df.shape

(100, 3)

In [6]:
x = df.drop(columns=['placed'])
# x

In [7]:
y = df['placed']
# y

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
x_train , x_test, y_train , y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [23]:
print("total shape or df:",df.shape)
print("-------**************---------")
print("total input data shape:,x.shape")
print("x_train data shape:",x_train.shape)
print("x_test data shape:",x_test.shape)
print("-------**************---------")
print("y_train data shape:",y_train.shape)
print("y_test data shape:",y_test.shape)

total shape or df: (100, 3)
-------**************---------
total input data shape:,x.shape
x_train data shape: (80, 2)
x_test data shape: (20, 2)
-------**************---------
y_train data shape: (80,)
y_test data shape: (20,)

In [11]:
# df(100,3) = x(100,2)+y(100,1)
# x(100,2)  = x_train(80,2) + x_test(20,2)
# y(100,1)  = y_train(80,1)+ y_tets(20,1)

In [12]:
# task covid dataset convert into categorical to numerical
# missing data handle
# df---> x,y,x_train,x_test,y_train,y_test

In [14]:
df1 = pd.read_csv("/content/covid_toy.csv")

In [15]:
df1.head(2)

   age gender  fever cough     city has_covid
0   60   Male  103.0  Mild  Kolkata        No
1   27   Male  100.0  Mild    Delhi       Yes

In [16]:
df1.shape

(100, 6)

In [17]:
df1.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [18]:
df1['fever'] = df1['fever'].fillna(df1['fever'].mean())

In [19]:
df1.isnull().sum()

age          0
gender       0
fever        0
cough        0
city         0
has_covid    0
dtype: int64

In [20]:
from sklearn.model_selection import train_test_split

In [21]:
df1 = pd.get_dummies(df1, columns=['gender'], dtype=int)

print(df1.head())

   age  fever cough     city has_covid  gender_Female  gender_Male
0   60  103.0  Mild  Kolkata        No              0            1
1   27  100.0  Mild    Delhi       Yes              0            1
2   42  101.0  Mild    Delhi        No              0            1
3   31   98.0  Mild  Kolkata        No              1            0
4   65  101.0  Mild   Mumbai        No              1            0