In [1]:
# introduction to pandas
# pandas is an open-source libery which is used for handle data manipulation

In [2]:
import pandas as pd

In [3]:
# data sturcture or pandas  --->
# (1). series ---> it is one dimensionl array and it return only values not column name
# (2). DataFrame ---> it is multi-dimensionl arrray and it return values with column name

In [4]:
# series

In [5]:
a = pd.Series([1,23,56,55])
a

0     1
1    23
2    56
3    55
dtype: int64

In [6]:
type(a)

pandas.core.series.Series

In [7]:
# DataFrame

In [8]:
a = {
    "emp_id":[1,2,3,4,5],
    "name":["shubh","shiv","hsus","hsid","djh"],
    "department":["it","sales","it","it","sales"],
    "working_houes":[3,6,8,3,3]

}

In [9]:
type(a)

dict

In [10]:
df = pd.DataFrame(a)
df

   emp_id   name department  working_houes
0       1  shubh         it              3
1       2   shiv      sales              6
2       3   hsus         it              8
3       4   hsid         it              3
4       5    djh      sales              3

In [11]:
#export this df into csv

In [12]:
df.to_csv("emp_data.csv")

In [13]:
df.to_csv("emp_data_new.csv",index=False)

In [14]:
#import this df using pandas

In [15]:
# click on files ---> click on 'upload to session stores' ---->
# select the data ----> click to open ---> click on triple dot and --->
# click on copy path ---> paste it into cell

In [16]:
df_1 = pd.read_csv("/content/emp_data.csv")

In [17]:
df_1

   Unnamed: 0  emp_id   name department  working_houes
0           0       1  shubh         it              3
1           1       2   shiv      sales              6
2           2       3   hsus         it              8
3           3       4   hsid         it              3
4           4       5    djh      sales              3